### ISSUE TITLE
Problems inflating RadioRealButton API 16

### ISSUE THREAD

**Issue by nam2017** [ceryle/RadioRealButton#19]
I am trying to run my app in Android 4.1.2 API 16 and i get this problem:

  java.lang.RuntimeException: Unable to start activity ComponentInfo{tkskoapps.com.preciodemedicamentos/tkskoapps.com.preciodemedicamentos.ui.activity.MainActivity}: android.view.InflateException: Binary XML file line #32: Error inflating class co.ceryle.radiorealbutton.library.RadioRealButton
                                                     at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2059)
                                                     at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2084)
                                                     at android.app.ActivityThread.access$600(ActivityThread.java:130)
                                                     at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1195)
                                                     at android.os.Handler.dispatchMessage(Handler.java:99)
                                                     at android.os.Looper.loop(Looper.java:137)
                                                     at android.app.ActivityThread.main(ActivityThread.java:4745)
                                                     at java.lang.reflect.Method.invokeNative(Native Method)
                                                     at java.lang.reflect.Method.invoke(Method.java:511)
                                                     at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:786)
                                                     at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:553)
                                                     at dalvik.system.NativeStart.main(Native Method)
                                                  Caused by: android.view.InflateException: Binary XML file line #32: Error inflating class co.ceryle.radiorealbutton.library.RadioRealButton
                                                     at android.view.LayoutInflater.createView(LayoutInflater.java:613)
                                                     at android.view.LayoutInflater.createViewFromTag(LayoutInflater.java:687)
                                                     at android.view.LayoutInflater.rInflate(LayoutInflater.java:746)
                                                     at android.view.LayoutInflater.rInflate(LayoutInflater.java:749)
                                                     at android.view.LayoutInflater.rInflate(LayoutInflater.java:749)
                                                     at android.view.LayoutInflater.inflate(LayoutInflater.java:489)
                                                     at android.view.LayoutInflater.inflate(LayoutInflater.java:396)
                                                     at tkskoapps.com.preciodemedicamentos.ui.fragment.SearchFragment.onCreateView(SearchFragment.java:82)
                                                     at android.support.v4.app.Fragment.performCreateView(Fragment.java:2189)
                                                     at android.support.v4.app.FragmentManagerImpl.moveToState(FragmentManager.java:1299)
                                                     at android.support.v4.app.FragmentManagerImpl.moveFragmentToExpectedState(FragmentManager.java:1528)
                                                     at android.support.v4.app.FragmentManagerImpl.moveToState(FragmentManager.java:1595)
                                                     at android.support.v4.app.BackStackRecord.executeOps(BackStackRecord.java:757)
                                                     at android.support.v4.app.FragmentManagerImpl.executeOps(FragmentManager.java:2355)
                                                     at android.support.v4.app.FragmentManagerImpl.executeOpsTogether(FragmentManager.java:2146)
                                                     at android.support.v4.app.FragmentManagerImpl.optimizeAndExecuteOps(FragmentManager.java:2098)
                                                     at android.support.v4.app.FragmentManagerImpl.execPendingActions(FragmentManager.java:2008)
                                                     at android.support.v4.app.FragmentController.execPendingActions(FragmentController.java:388)
                                                     at android.support.v4.app.FragmentActivity.onStart(FragmentActivity.java:607)
                                                     at android.support.v7.app.AppCompatActivity.onStart(AppCompatActivity.java:178)
                                                     at android.app.Instrumentation.callActivityOnStart(Instrumentation.java:1163)
                                                     at android.app.Activity.performStart(Activity.java:5018)
                                                     at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2032)
                                                     at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2084) 
                                                     at android.app.ActivityThread.access$600(ActivityThread.java:130) 
                                                     at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1195) 
                                                     at android.os.Handler.dispatchMessage(Handler.java:99) 
                                                     at android.os.Looper.loop(Looper.java:137) 
                                                     at android.app.ActivityThread.main(ActivityThread.java:4745) 
                                                     at java.lang.reflect.Method.invokeNative(Native Method) 
                                                     at java.lang.reflect.Method.invoke(Method.java:511) 
                                                     at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:786) 
                                                     at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:553) 
                                                     at dalvik.system.NativeStart.main(Native Method) 
                                                  Caused by: java.lang.reflect.InvocationTargetException
                                                     at java.lang.reflect.Constructor.constructNative(Native Method)
                                                     at java.lang.reflect.Constructor.newInstance(Constructor.java:417)
                                                     at android.view.LayoutInflater.createView(LayoutInflater.java:587)
                                                     at android.view.LayoutInflater.createViewFromTag(LayoutInflater.java:687) 
                                                     at android.view.LayoutInflater.rInflate(LayoutInflater.java:746) 
                                                     at android.view.LayoutInflater.rInflate(LayoutInflater.java:749) 
                                                     at android.view.LayoutInflater.rInflate(LayoutInflater.java:749) 
                                                     at android.view.LayoutInflater.inflate(LayoutInflater.java:489) 
                                                     at android.view.LayoutInflater.inflate(LayoutInflater.java:396) 
                                                     at tkskoapps.com.preciodemedicamentos.ui.fragment.SearchFragment.onCreateView(SearchFragment.java:82) 
                                                     at android.support.v4.app.Fragment.performCreateView(Fragment.java:2189) 
                                                     at android.support.v4.app.FragmentManagerImpl.moveToState(FragmentManager.java:1299) 
                                                     at android.support.v4.app.FragmentManagerImpl.moveFragmentToExpectedState(FragmentManager.java:1528) 
                                                     at android.support.v4.app.FragmentManagerImpl.moveToState(FragmentManager.java:1595) 
                                                     at android.support.v4.app.BackStackRecord.executeOps(BackStackRecord.java:757) 
                                                     at android.support.v4.app.FragmentManagerImpl.executeOps(FragmentManager.java:2355) 
                                                     at android.support.v4.app.FragmentManagerImpl.executeOpsTogether(FragmentManager.java:2146) 
                                                     at android.support.v4.app.FragmentManagerImpl.optimizeAndExecuteOps(FragmentManager.java:2098) 
                                                     at android.support.v4.app.FragmentManagerImpl.execPendingActions(FragmentManager.java:2008) 
                                                     at android.support.v4.app.FragmentController.execPendingActions(FragmentController.java:388) 
                                                     at android.support.v4.app.FragmentActivity.onStart(FragmentActivity.java:607) 
                                                     at android.support.v7.app.AppCompatActivity.onStart(AppCompatActivity.java:178) 
                                                     at android.app.Instrumentation.callActivityOnStart(Instrumentation.java:1163) 
                                                     at android.app.Activity.performStart(Activity.java:5018) 
                                                     at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2032) 
                                                     at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2084) 
                                                     at android.app.ActivityThread.access$600(ActivityThread.java:130) 
                                                     at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1195) 
                                                     at android.os.Handler.dispatchMessage(Handler.java:99) 
                                                     at android.os.Looper.loop(Looper.java:137) 
                                                     at android.app.ActivityThread.main(ActivityThread.java:4745) 
                                                     at java.lang.reflect.Method.invokeNative(Native Method) 
                                                     at java.lang.reflect.Method.invoke(Method.java:511) 
                                                     at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:786) 
                                                     at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:553) 
                                                     at dalvik.system.NativeStart.main(Native Method) 
                                                  Caused by: java.lang.NullPointerException
                                                     at co.ceryle.radiorealbutton.library.RadioRealButton.updatePadding(RadioRealButton.java:473)
                                                     at co.ceryle.radiorealbutton.library.RadioRealButton.updatePaddings(RadioRealButton.java:456)
                                                     at co.ceryle.radiorealbutton.library.RadioRealButton.setPadding(RadioRealButton.java:451)
                                                     at android.view.View.recomputePadding(View.java:10914)
                                                     at android.view.View.resolvePadding(View.java:11584)
                                                     at android.view.View.resolveLayoutDirection(View.java:11524)
                                                     at android.view.View.getResolvedLayoutDirection(View.java:5708)
                                                     at android.view.View.requestLayout(View.java:15125)
                                                     at android.view.View.setLayoutParams(View.java:9904)
                                                 	at co.ceryle.radiorealbutton.library.RadioRealBu

What can i do? It works fine on ANdroid 5, 6, 7 but i am having problems with API 16.

 thanks!

**Comment by ceryle** [comment]
Hi nam2017,
I released a quick fix for that error and, I believe it is fixed. However, if you encounter any issue about setting buttons' padding, please write here.
