### ISSUE TITLE
Calling deselect() twice in a row reselects old value

### ISSUE THREAD

**Issue by stephen-workpop** [ceryle/RadioRealButton#21]
I have noticed that calling deselect() deselects any selected value as expected. However, if it is called again, the radio button that was last selected is re-selected.

**Comment by ceryle** [comment]
Hi stephen,
I will fix that issue in the next release, thanks for informing.

**Comment by stephen-workpop** [comment]
Thank you! Let me know if you need help with reproducing the issue.

**Comment by ceryle** [comment]
Hi, 
Thanks. I fixed the issue and it should be working properly now.

**Comment by stephen-workpop** [comment]
Thank you for the quick fix. It seems to be working now. Unfortunately, if you call deselect() when  nothing is selected, you get a crash. This may be by design, but I personally feel the method should be a little more resilient. 

In the following stack, I am calling deselect() on aRadioRealButtonGroup that does not have a currently selected value during the creation of my Activity. This causes an index out-of-bounds crash. For now, I am just making sure that getPosition != -1 before calling deselect() to avoid this crash.

`04-28 11:06:45.147 15986-15986/com.workpop.emp.debug E/AndroidRuntime: FATAL EXCEPTION: main
                                                                       Process: com.workpop.emp.debug, PID: 15986
                                                                       java.lang.RuntimeException: Unable to start activity ComponentInfo{com.workpop.emp.debug/com.workpop.emp.flows.review.CandidateReviewFilterActivity}: java.lang.ArrayIndexOutOfBoundsException: length=12; index=-1
                                                                           at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2416)
                                                                           at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2476)
                                                                           at android.app.ActivityThread.-wrap11(ActivityThread.java)
                                                                           at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1344)
                                                                           at android.os.Handler.dispatchMessage(Handler.java:102)
                                                                           at android.os.Looper.loop(Looper.java:148)
                                                                           at android.app.ActivityThread.main(ActivityThread.java:5417)
                                                                           at java.lang.reflect.Method.invoke(Native Method)
                                                                           at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:726)
                                                                           at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:616)
                                                                        Caused by: java.lang.ArrayIndexOutOfBoundsException: length=12; index=-1
                                                                           at java.util.ArrayList.get(ArrayList.java:310)
                                                                           at co.ceryle.radiorealbutton.library.RadioRealButtonGroup.deselect(RadioRealButtonGroup.java:611)
                                                                           at com.workpop.emp.flows.review.CandidateReviewFilterActivity.initializeUIFromCurrentFilterValues(CandidateReviewFilterActivity.java:279)
                                                                           at com.workpop.emp.flows.review.CandidateReviewFilterActivity.onCreate(CandidateReviewFilterActivity.java:257)
                                                                           at android.app.Activity.performCreate(Activity.java:6251)
                                                                           at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1107)
                                                                           at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2369)
                                                                           at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2476) 
                                                                           at android.app.ActivityThread.-wrap11(ActivityThread.java) 
                                                                           at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1344) 
                                                                           at android.os.Handler.dispatchMessage(Handler.java:102) 
                                                                           at android.os.Looper.loop(Looper.java:148) 
                                                                           at android.app.ActivityThread.main(ActivityThread.java:5417) 
                                                                           at java.lang.reflect.Method.invoke(Native Method) 
                                                                           at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:726) 
                                                                           at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:616) `

**Comment by ceryle** [comment]
Hi,
Sorry for that, it is now working as expected this time.

**Comment by stephen-workpop** [comment]
Thanks!
