### ISSUE TITLE
Change button position in code

### ISSUE THREAD

**Issue by dca-ps** [ceryle/RadioRealButton#3]
Hi.
Firstly I want to thank and congratulate you for the library. Very good work!
Now, the problem. I need to change the selected button during the execution of the code. I'm trying to use the setSelected method, but it only works on the onCreate, the first time I call it. Am I doing something wrong ?

**Comment by ceryle** [comment]
Hello, 
Thank you for your kind words. It gets better with your help. No, you didn't do anything wrong. Actually that method had missing lines in it. I released a new version of the library and in sample project I added setPosition example.
Have a nice day.

**Comment by dca-ps** [comment]
Man, after the update, this error keep showing and my app doesnt open anymore. I didn't do anything to my code, I just updated your library. Can you please take a look at it ?
`09-25 22:04:58.497 1989-1989/com.example.teste.test E/AndroidRuntime: Error reporting crash
                                                                                        java.lang.OutOfMemoryError: Failed to allocate a 32855856 byte allocation with 16777216 free bytes and 29MB until OOM
                                                                                            at java.lang.AbstractStringBuilder.enlargeBuffer(AbstractStringBuilder.java:95)
                                                                                            at java.lang.AbstractStringBuilder.append0(AbstractStringBuilder.java:125)
                                                                                            at java.lang.StringBuffer.append(StringBuffer.java:278)
                                                                                            at java.io.StringWriter.write(StringWriter.java:123)
                                                                                            at com.android.internal.util.FastPrintWriter.flushLocked(FastPrintWriter.java:358)
                                                                                            at com.android.internal.util.FastPrintWriter.appendLocked(FastPrintWriter.java:303)
                                                                                            at com.android.internal.util.FastPrintWriter.write(FastPrintWriter.java:625)
                                                                                            at com.android.internal.util.FastPrintWriter.append(FastPrintWriter.java:658)
                                                                                            at java.io.PrintWriter.append(PrintWriter.java:691)
                                                                                            at java.io.PrintWriter.append(PrintWriter.java:687)
                                                                                            at java.io.Writer.append(Writer.java:198)
                                                                                            at java.lang.Throwable.printStackTrace(Throwable.java:324)
                                                                                            at java.lang.Throwable.printStackTrace(Throwable.java:300)
                                                                                            at android.util.Log.getStackTraceString(Log.java:343)
                                                                                            at com.android.internal.os.RuntimeInit.Clog_e(RuntimeInit.java:61)
                                                                                            at com.android.internal.os.RuntimeInit.-wrap0(RuntimeInit.java)
                                                                                            at com.android.internal.os.RuntimeInit$UncaughtHandler.uncaughtException(RuntimeInit.java:86)
                                                                                            at java.lang.ThreadGroup.uncaughtException(ThreadGroup.java:693)
                                                                                            at java.lang.ThreadGroup.uncaughtException(ThreadGroup.java:690)`

**Comment by ceryle** [comment]
It is really interesting, there shouldn't be any problem at all. I tested on three different devices and one of them was really old. This error could be due to size of the images that you use. You can try putting your images in drawable-nodpi folder or resize them. Or if you are trying to do everything programmatically, it may cause "out of memory" problem. You can use threads like post(new Runnable()){... If the problem continues, please inform me.

**Comment by dca-ps** [comment]
I tried a few iterations of my code. The problem was not the size of the icon, it was the setPositionWithAnimation method. The change without the animation is working properly. Anyway, thank you very much for your time!

**Comment by ceryle** [comment]
Thank you for informing me. It is good to hear that it works with the other method. I will try to fix animate method in next release.
Happy coding.
